### ISSUE TITLE
__init__.py names space issue

### ISSUE THREAD

**Issue by draperjames** [zbarge/zeex#3]
When running setup.py in my py34 env with pyside installed I got the following error;
![zeex_namespace_issue](https://cloud.githubusercontent.com/assets/22569604/21187263/52687eb4-c1e5-11e6-8221-f1e9e803a8b7.PNG)

I think all that you need to do is add a blank __init__.py file to the top level dir.

**Comment by draperjames** [comment]
Actually adding a blank init file doesn't work.

**Comment by zbarge** [comment]
Hmm...yeah i havent tested doing the install setup.py
you will probably just want to pip install the individual packages for the
moment...i will have to figure out how to fix that.

**Comment by zbarge** [comment]
It's fixed - git fetch/pull from the master and try what you did again...it should work no problems now.
