### ISSUE TITLE
DataModelManager.py missing

### ISSUE THREAD

**Issue by draperjames** [zbarge/zeex#4]
So I merged your commits recommended at the end of #3 and now I'm able to run `python setup.py install` but IDK how to call it through there. So I tried to just run `zeex_app.py` through the command prompt and I got the following error;

![zeex_issue_2](https://cloud.githubusercontent.com/assets/22569604/21193813/9123b2e8-c1fb-11e6-8de8-70b4e0eb3701.PNG)

**Comment by draperjames** [comment]
Wait is that on yr new fork? I'll bet that's what it is. Let me check out and pip install yr fork.

**Comment by draperjames** [comment]
I keep on getting import errors that trace back to a sip import somewhere in qtpandas. 
I guess that [sip](https://pypi.python.org/pypi/SIP) was develop by riverbankcomputing for use with PyQt. So I think in a Pyside based env that you can't use very well even if you install it. BTW here is how to install it by itself; `pip3 install sip`  😐
IDK what's happening. It may be the fact that I'm trying to do all of this in a conda env. IDK still trying to figure it out I'll keep testing.

**Comment by zbarge** [comment]
Ah dang yeah DataFrameModelManager was pending your approval to merge. Looks like you took care of it. Ill keep this issue open with the purpose of figuring out the sip issue.

**Comment by zbarge** [comment]
Closing this issue as sip_import fix is being handled in [qtpandas-Issue #30](https://github.com/draperjames/qtpandas/pull/30) and DataFrameModelManager has been added to qtpandas - master branch.
